### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-html-intro#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://thankfulfeet.surge.sh).

**Comment by KatieMFritz** [comment]
Sorry! It's actually [here](http://thankful-feet.surge.sh).

**Comment by chrisvfritz** [comment]
Great work! You can definitely :shipit:. I especially like the semantic HTML elements you're already using. :smiley: I always like to find _some_ room for improvement though, so here are a couple nitpicks:
- On [the closing body tag](https://github.com/KatieMFritz/codelab-html-intro/blob/master/index.html#L35-L36), it looks like there's a new line before the closing `>` - probably just a typo and it won't cause any problems - it's purely a readability concern.
- And one more thing that isn't technically wrong, but a style nitpick. In modern HTML, a [self-closing image tag](https://github.com/KatieMFritz/codelab-html-intro/blob/master/index.html#L10) doesn't technically need the slash at the end - just like you left it off of the `<br>` and that's still valid.

These are very tiny nitpicks. Overall, I'm very impressed with the work you've put in. I would definitely hire this cat!! :smile_cat:
